# Generated by Django 3.1.1 on 2020-09-02 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PF2', '0003_auto_20200818_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 17, 26, 21, 520361, tzinfo=utc)),
        ),
    ]
