# Generated by Django 3.1.2 on 2020-10-29 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PF2', '0004_auto_20200902_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 8, 17, 10, 491765, tzinfo=utc)),
        ),
    ]
